#!/bin/sh

# Ask for password before running anything
sudo -v

curl https://raw.githubusercontent.com/dcyoung-dev/laptop-setup/work-je/laptop_local --output ~/.laptop.local

curl -s https://raw.githubusercontent.com/junipereducation/laptop-setup/main/mac | sh 2>&1 | tee ~/laptop.log

curl -s https://raw.githubusercontent.com/dcyoung-dev/mac-setup/master/config/macos.sh | sh 2>&1 | tee ~/laptop_config.log
