name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: curl --remote-name https://raw.githubusercontent.com/dcyoung-dev/laptop-setup/main/setup
